version: '3'
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cashback
      POSTGRES_PASSWORD: cashback
      POSTGRES_DB: cashback-db

volumes:
  database-data:

